### ISSUE TITLE
About dataset

### ISSUE THREAD

**Issue by mzy97** [jspenmar/DeFeat-Net#5]
Hi, thank you for sharing this wonderful work.
In paper you said:" To resolve this, we returned to the original RobotCar dataset and manually created a validation dataset comprising of 12,000 images with their corresponding ground-truth LiDAR depth maps, split evenly across day and night driving scenarios.

Could you share this dataset?

**Comment by jspenmar** [comment]
Hi,

We use sequence "2015-08-27-10-06-57" as the daytime data and "2014-12-16-18-44-24" as the night-time data. 
We downsample the number of images in each sequence by a factor of 5 and use the left & right stereo images. 
The depth values are obtained by using the original [RobotCar devkit](https://github.com/ori-mrg/robotcar-dataset-sdk).

Hope this helps,
Jaime
